PRODUCT_COPY_FILES += \
    vendor/gapps/gapps/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
    vendor/gapps/gapps/system/app/ChromeBookmarksSyncAdapter.apk:system/app/ChromeBookmarksSyncAdapter.apk \
    vendor/gapps/gapps/system/app/GenieWidget.apk:system/app/GenieWidget.apk \
    vendor/gapps/gapps/system/app/Gmail.apk:system/app/Gmail.apk \
    vendor/gapps/gapps/system/app/GmsCore.apk:system/app/GmsCore.apk \
    vendor/gapps/gapps/system/app/GoogleBackupTransport.apk:system/app/GoogleBackupTransport.apk \
    vendor/gapps/gapps/system/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk \
    vendor/gapps/gapps/system/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk \
    vendor/gapps/gapps/system/app/GoogleEars.apk:system/app/GoogleEars.apk \
    vendor/gapps/gapps/system/app/GoogleFeedback.apk:system/app/GoogleFeedback.apk \
    vendor/gapps/gapps/system/app/GoogleLoginService.apk:system/app/GoogleLoginService.apk \
    vendor/gapps/gapps/system/app/GooglePartnerSetup.apk:system/app/GooglePartnerSetup.apk \
    vendor/gapps/gapps/system/app/GoogleServicesFramework.apk:system/app/GoogleServicesFramework.apk \
    vendor/gapps/gapps/system/app/GoogleTTS.apk:system/app/GoogleTTS.apk \
    vendor/gapps/gapps/system/app/LatinImeDictionaryPack.apk:system/app/LatinImeDictionaryPack.apk \
    vendor/gapps/gapps/system/app/MediaUploader.apk:system/app/MediaUploader.apk \
    vendor/gapps/gapps/system/app/NetworkLocation.apk:system/app/NetworkLocation.apk \
    vendor/gapps/gapps/system/app/OneTimeInitializer.apk:system/app/OneTimeInitializer.apk \
    vendor/gapps/gapps/system/app/Phonesky.apk:system/app/Phonesky.apk \
    vendor/gapps/gapps/system/app/QuickSearchBox.apk:system/app/QuickSearchBox.apk \
    vendor/gapps/gapps/system/app/SetupWizard.apk:system/app/SetupWizard.apk \
    vendor/gapps/gapps/system/app/Talk.apk:system/app/Talk.apk \
    vendor/gapps/gapps/system/app/Talkback.apk:system/app/Talkback.apk \
    vendor/gapps/gapps/system/app/VoiceSearchStub.apk:system/app/VoiceSearchStub.apk \
    vendor/gapps/gapps/system/app/Wallet.apk:system/app/Wallet.apk \
    vendor/gapps/gapps/system/etc/g.prop:system/etc/g.prop \
    vendor/gapps/gapps/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/gapps/gapps/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
    vendor/gapps/gapps/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
    vendor/gapps/gapps/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
    vendor/gapps/gapps/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
    vendor/gapps/gapps/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
    vendor/gapps/gapps/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
    vendor/gapps/gapps/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
    vendor/gapps/gapps/system/lib/libflint_engine_jni_api.so:system/lib/libflint_engine_jni_api.so \
    vendor/gapps/gapps/system/lib/libfrsdk.so:system/lib/libfrsdk.so \
    vendor/gapps/gapps/system/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
    vendor/gapps/gapps/system/lib/libgoogle_recognizer_jni.so:system/lib/libgoogle_recognizer_jni.so \
    vendor/gapps/gapps/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
    vendor/gapps/gapps/system/lib/libpicowrapper.so:system/lib/libpicowrapper.so \
    vendor/gapps/gapps/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
    vendor/gapps/gapps/system/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
    vendor/gapps/gapps/system/lib/libvideochat_stabilize.so:system/lib/libvideochat_stabilize.so \
    vendor/gapps/gapps/system/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
    vendor/gapps/gapps/system/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so \
    vendor/gapps/gapps/system/tts/lang_pico/de-DE_gl0_sg.bin:system/tts/lang_pico/de-DE_gl0_sg.bin \
    vendor/gapps/gapps/system/tts/lang_pico/de-DE_ta.bin:system/tts/lang_pico/de-DE_ta.bin \
    vendor/gapps/gapps/system/tts/lang_pico/es-ES_ta.bin:system/tts/lang_pico/es-ES_ta.bin \
    vendor/gapps/gapps/system/tts/lang_pico/es-ES_zl0_sg.bin:system/tts/lang_pico/es-ES_zl0_sg.bin \
    vendor/gapps/gapps/system/tts/lang_pico/fr-FR_nk0_sg.bin:system/tts/lang_pico/fr-FR_nk0_sg.bin \
    vendor/gapps/gapps/system/tts/lang_pico/fr-FR_ta.bin:system/tts/lang_pico/fr-FR_ta.bin \
    vendor/gapps/gapps/system/tts/lang_pico/it-IT_cm0_sg.bin:system/tts/lang_pico/it-IT_cm0_sg.bin \
    vendor/gapps/gapps/system/tts/lang_pico/it-IT_ta.bin:system/tts/lang_pico/it-IT_ta.bin \
    vendor/gapps/gapps/system/usr/srec/en-US/acoustic_model:system/usr/srec/en-US/acoustic_model \
    vendor/gapps/gapps/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/gapps/gapps/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
    vendor/gapps/gapps/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/gapps/gapps/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/gapps/gapps/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/gapps/gapps/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/gapps/gapps/system/usr/srec/en-US/embed_phone_nn_model:system/usr/srec/en-US/embed_phone_nn_model \
    vendor/gapps/gapps/system/usr/srec/en-US/embed_phone_nn_state_sym:system/usr/srec/en-US/embed_phone_nn_state_sym \
    vendor/gapps/gapps/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/gapps/gapps/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/gapps/gapps/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
    vendor/gapps/gapps/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/gapps/gapps/system/usr/srec/en-US/google_hotword.config:system/usr/srec/en-US/google_hotword.config \
    vendor/gapps/gapps/system/usr/srec/en-US/google_hotword_clg:system/usr/srec/en-US/google_hotword_clg \
    vendor/gapps/gapps/system/usr/srec/en-US/google_hotword_logistic:system/usr/srec/en-US/google_hotword_logistic \
    vendor/gapps/gapps/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/gapps/gapps/system/usr/srec/en-US/hmmsyms:system/usr/srec/en-US/hmmsyms \
    vendor/gapps/gapps/system/usr/srec/en-US/hotword_symbols:system/usr/srec/en-US/hotword_symbols \
    vendor/gapps/gapps/system/usr/srec/en-US/lintrans_model:system/usr/srec/en-US/lintrans_model \
    vendor/gapps/gapps/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/gapps/gapps/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/gapps/gapps/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
    vendor/gapps/gapps/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
    vendor/gapps/gapps/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/gapps/gapps/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
    vendor/gapps/gapps/system/usr/srec/en-US/symbols:system/usr/srec/en-US/symbols
